import { useEffect, useMemo, useState } from 'react';
import { transform, type Json, type TransformOperation } from '../shared/json';
import { diffJson } from '../shared/diff';
import { MASK, redactText, sensitivePath } from '../shared/redaction';
import type { TransformProfile } from '../shared/workspaces';
import { deleteDocument, getConfiguration, putDocument } from './api';
import DiffPanel from './DiffPanel';
export default function TransformPanel({ text, apply }: { text: string; apply: (text: string) => void }) {
  const [operations, setOperations] = useState<TransformOperation[]>([]); const [profiles, setProfiles] = useState<TransformProfile[]>([]); const [profileId, setProfileId] = useState(''); const [name, setName] = useState('');
  const [message, setMessage] = useState(''); const [preview, setPreview] = useState(false); const [reveal, setReveal] = useState(false); const [invalid, setInvalid] = useState<Record<string, string>>({});
  useEffect(() => { void getConfiguration().then((c) => setProfiles(c.transformations)).catch(() => setMessage('Configuration unavailable.')); }, []);
  const result = useMemo(() => { try { return transform(JSON.parse(text), operations); } catch { return { error: { step: 0, message: 'Invalid JSON body.' } }; } }, [text, operations]);
  const change = (next: TransformOperation[]) => { setOperations(next); setPreview(false); };
  const update = (i: number, patch: Partial<TransformOperation>) => change(operations.map((op, index) => index === i ? { ...op, ...patch } : op));
  const save = async () => { try { if (Object.keys(invalid).length) throw new Error('Fix invalid JSON values.'); const value = await putDocument('transformations', { id: profileId || crypto.randomUUID(), name, operations });
    setProfiles((old) => [...old.filter((p) => p.id !== value.id), value]); setProfileId(value.id); setMessage('Pipeline saved.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to save.'); } };
  const output = result.value === undefined ? '' : JSON.stringify(result.value, null, 2);
  return <section className="transform-panel"><div className="section-heading"><h3>JSON transformations</h3><button className="text-button" type="button" disabled={operations.length >= 100} onClick={() => change([...operations, { id: crypto.randomUUID(), enabled: true, type: 'set', path: '$.campo', value: null }])}>Add operation</button></div>
    <div className="action-bar"><select aria-label="Saved pipeline" value={profileId} onChange={(e) => { setProfileId(e.target.value); const p = profiles.find((p) => p.id === e.target.value); change(p?.operations ?? []); setInvalid({}); setName(p?.name ?? ''); }}><option value="">New pipeline</option>{profiles.map((p) => <option value={p.id} key={p.id}>{p.name}</option>)}</select><input aria-label="Pipeline name" placeholder="Pipeline name" value={name} onChange={(e) => setName(e.target.value)} /><button className="text-button" type="button" onClick={() => { void save(); }}>Save pipeline</button>{profileId && <button className="text-button" type="button" onClick={() => { void deleteDocument('transformations', profileId).then(() => { setProfiles(profiles.filter((p) => p.id !== profileId)); setProfileId(''); setMessage('Pipeline deleted.'); }).catch((e: unknown) => setMessage(e instanceof Error ? e.message : 'Failed.')); }}>Delete pipeline</button>}</div>
    {operations.map((op, i) => <div className="transform-operation" key={op.id}><span>{i + 1}</span><input type="checkbox" aria-label={`Enable operation ${i + 1}`} checked={op.enabled} onChange={(e) => update(i, { enabled: e.target.checked })} /><select aria-label={`Operation ${i + 1}`} value={op.type} onChange={(e) => update(i, { type: e.target.value as TransformOperation['type'], value: op.value ?? null, name: op.name ?? '' })}><option value="set">Set</option><option value="delete">Delete</option><option value="rename">Rename</option></select><input aria-label={`Path ${i + 1}`} value={op.path} onChange={(e) => update(i, { path: e.target.value })} />
      {op.type === 'set' && <input key={`${op.id}-${profileId}`} aria-label={`JSON value ${i + 1}`} type={!reveal && (sensitivePath(op.path) || redactText(JSON.stringify(op.value) ?? '').includes(MASK)) ? 'password' : 'text'} defaultValue={JSON.stringify(op.value)} onChange={(e) => { try { const value: unknown = JSON.parse(e.target.value); update(i, { value: value as Json }); setInvalid((old) => { const next = { ...old }; delete next[op.id]; return next; }); } catch { setInvalid((old) => ({ ...old, [op.id]: `Step ${i + 1}: invalid JSON value.` })); setPreview(false); } }} />}
      {op.type === 'rename' && <input aria-label={`New name ${i + 1}`} value={op.name ?? ''} onChange={(e) => update(i, { name: e.target.value })} />}
      <button className="text-button" type="button" disabled={i === 0} aria-label={`Move operation up ${i + 1}`} onClick={() => { const next = [...operations]; [next[i - 1], next[i]] = [next[i]!, next[i - 1]!]; change(next); }}>↑</button><button className="text-button" type="button" disabled={i === operations.length - 1} aria-label={`Move operation down ${i + 1}`} onClick={() => { const next = [...operations]; [next[i], next[i + 1]] = [next[i + 1]!, next[i]!]; change(next); }}>↓</button><button className="text-button" type="button" aria-label={`Remove operation ${i + 1}`} onClick={() => { change(operations.filter((_, n) => n !== i)); setInvalid((old) => { const next = { ...old }; delete next[op.id]; return next; }); }}>×</button></div>)}
    <button className="text-button" type="button" onClick={() => setReveal(!reveal)}>{reveal ? 'Hide values' : 'Reveal operation values'}</button><p className="muted">Operations run from top to bottom. Set requires existing parents and can append to arrays. Delete shifts array indices. Rename stays within the same object.</p>
    {result.error && <p className="notice warning" role="alert">Step {result.error.step}: {result.error.message}</p>}{Object.values(invalid).map((error) => <p className="notice warning" role="alert" key={error}>{error}</p>)}
    <button className="text-button" type="button" disabled={!!result.error || !!Object.keys(invalid).length} onClick={() => setPreview(true)}>Transformation preview</button>
    {preview && result.value !== undefined && <><button className="text-button" type="button" onClick={() => setReveal(!reveal)}>{reveal ? 'Hide sensitive values' : 'Reveal sensitive values'}</button><div className="diff-columns"><div><h4>Original</h4><pre className="code-block">{reveal ? text : redactText(text)}</pre></div><div><h4>Transformed</h4><pre className="code-block">{reveal ? output : redactText(output)}</pre></div></div><DiffPanel result={diffJson(JSON.parse(text), result.value)} left="Original" right="Transformed" /><button className="text-button" type="button" onClick={() => { apply(output); setPreview(false); setOperations([]); setProfileId(''); setName(''); setInvalid({}); }}>Use preview in editor</button><p className="muted">Review the editor and run replay explicitly. The original event is preserved.</p></>}
    {message && <p role="status">{message}</p>}
  </section>;
}
